# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lockna/CLionProjects/hawk/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lockna/CLionProjects/hawk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lockna/CLionProjects/hawk/CMakeFiles /home/lockna/CLionProjects/hawk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lockna/CLionProjects/hawk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hawk

# Build rule for target.
hawk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hawk
.PHONY : hawk

# fast build rule for target.
hawk/fast:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/build
.PHONY : hawk/fast

collections/c_list.o: collections/c_list.c.o

.PHONY : collections/c_list.o

# target to build an object file
collections/c_list.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/c_list.c.o
.PHONY : collections/c_list.c.o

collections/c_list.i: collections/c_list.c.i

.PHONY : collections/c_list.i

# target to preprocess a source file
collections/c_list.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/c_list.c.i
.PHONY : collections/c_list.c.i

collections/c_list.s: collections/c_list.c.s

.PHONY : collections/c_list.s

# target to generate assembly for a file
collections/c_list.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/c_list.c.s
.PHONY : collections/c_list.c.s

collections/stack.o: collections/stack.c.o

.PHONY : collections/stack.o

# target to build an object file
collections/stack.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/stack.c.o
.PHONY : collections/stack.c.o

collections/stack.i: collections/stack.c.i

.PHONY : collections/stack.i

# target to preprocess a source file
collections/stack.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/stack.c.i
.PHONY : collections/stack.c.i

collections/stack.s: collections/stack.c.s

.PHONY : collections/stack.s

# target to generate assembly for a file
collections/stack.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/stack.c.s
.PHONY : collections/stack.c.s

collections/symtable.o: collections/symtable.c.o

.PHONY : collections/symtable.o

# target to build an object file
collections/symtable.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/symtable.c.o
.PHONY : collections/symtable.c.o

collections/symtable.i: collections/symtable.c.i

.PHONY : collections/symtable.i

# target to preprocess a source file
collections/symtable.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/symtable.c.i
.PHONY : collections/symtable.c.i

collections/symtable.s: collections/symtable.c.s

.PHONY : collections/symtable.s

# target to generate assembly for a file
collections/symtable.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/symtable.c.s
.PHONY : collections/symtable.c.s

collections/t_list.o: collections/t_list.c.o

.PHONY : collections/t_list.o

# target to build an object file
collections/t_list.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/t_list.c.o
.PHONY : collections/t_list.c.o

collections/t_list.i: collections/t_list.c.i

.PHONY : collections/t_list.i

# target to preprocess a source file
collections/t_list.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/t_list.c.i
.PHONY : collections/t_list.c.i

collections/t_list.s: collections/t_list.c.s

.PHONY : collections/t_list.s

# target to generate assembly for a file
collections/t_list.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/collections/t_list.c.s
.PHONY : collections/t_list.c.s

compiler/lexer.o: compiler/lexer.c.o

.PHONY : compiler/lexer.o

# target to build an object file
compiler/lexer.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/compiler/lexer.c.o
.PHONY : compiler/lexer.c.o

compiler/lexer.i: compiler/lexer.c.i

.PHONY : compiler/lexer.i

# target to preprocess a source file
compiler/lexer.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/compiler/lexer.c.i
.PHONY : compiler/lexer.c.i

compiler/lexer.s: compiler/lexer.c.s

.PHONY : compiler/lexer.s

# target to generate assembly for a file
compiler/lexer.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/compiler/lexer.c.s
.PHONY : compiler/lexer.c.s

compiler/parser.o: compiler/parser.c.o

.PHONY : compiler/parser.o

# target to build an object file
compiler/parser.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/compiler/parser.c.o
.PHONY : compiler/parser.c.o

compiler/parser.i: compiler/parser.c.i

.PHONY : compiler/parser.i

# target to preprocess a source file
compiler/parser.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/compiler/parser.c.i
.PHONY : compiler/parser.c.i

compiler/parser.s: compiler/parser.c.s

.PHONY : compiler/parser.s

# target to generate assembly for a file
compiler/parser.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/compiler/parser.c.s
.PHONY : compiler/parser.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/hawk.dir/build.make CMakeFiles/hawk.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... hawk"
	@echo "... edit_cache"
	@echo "... collections/c_list.o"
	@echo "... collections/c_list.i"
	@echo "... collections/c_list.s"
	@echo "... collections/stack.o"
	@echo "... collections/stack.i"
	@echo "... collections/stack.s"
	@echo "... collections/symtable.o"
	@echo "... collections/symtable.i"
	@echo "... collections/symtable.s"
	@echo "... collections/t_list.o"
	@echo "... collections/t_list.i"
	@echo "... collections/t_list.s"
	@echo "... compiler/lexer.o"
	@echo "... compiler/lexer.i"
	@echo "... compiler/lexer.s"
	@echo "... compiler/parser.o"
	@echo "... compiler/parser.i"
	@echo "... compiler/parser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

